### PR TITLE
Replace System.String with ReadOnlySpan<System.Char> in Utf8YamlEmitter.WriteString

### PR DESCRIPTION
**Pull request by ArchLeaders**
Changes the input parameter of [`Utf8YamlEmitter.WriteString`](https://github.com/hadashiA/VYaml/blob/master/VYaml/Emitter/Utf8YamlEmitter.cs#L606) from `System.String` to `System.ReadOnlySpan<char>` for more optimal writing scenarios.

***Note, this PR changes the project `LangVersion` from `9` to `11` to use pattern matching on a `ReadOnlySpan<char>`.***

### CODE REVIEW

**Comment by hadashiA** [comment]
@ArchLeaders Ok thanks. 

There is one problem, however.

Currently, We need to write it in C# 9 because it shares source code with the Unity package.
Is it possible to get it to compile through the Unity environment?

I would like to check on my end, but it will be a bit later.

**Comment by CyberAndrii** [comment]
Hi @hadashiA!

Is there any reason to compile it through Unity instead of using a precompiled dll? If it needs some Unity APIs you could reference Unity's dlls in csproj (but don't ship them with the package). That's how I usually do it in my projects.

Also, changing type of a parameter is a breaking change and I really hate when projects do that. Please add the original method back as an overload.

**Comment by ArchLeaders** [comment]
> Also, changing type of a parameter is a breaking change and I really hate when projects do that. Please add the original method back as an overload.

Makes sense, although `string` can be implicitly converted to `ReadOnlySpan<char>` so it won't break anything.

**Comment by hadashiA** [comment]
Hi,

> Is there any reason to compile it through Unity instead of using a precompiled dll? If it needs some Unity APIs you could reference Unity's dlls in csproj (but don't ship them with the package). That's how I usually do it in my projects.

Ah yes,, perhaps we could distribute the dlls.
Source code distribution may have the advantage that it is easier for users to debug and understand. However, when I developed this, there was not much difference in compilers between .NET and Unity, but not so much now.
I think I'll switch to the Dll distribution.

> Also, changing type of a parameter is a breaking change and I really hate when projects do that. Please add the original method back as an overload.

👍

**Comment by rube200** [comment]
> Makes sense, although `string` can be implicitly converted to `ReadOnlySpan<char>` so it won't break anything.

I am not sure but i think it still breaks, you will need to recompile the project that refs on that case

**Comment by hadashiA** [comment]
In #114, I've been added `ReadOnlySpan<char>` overloads.  
The dll distribution is a major change. I would like to discuss it in a separate issue. Thanks.

**Pull request closed without merging**
